import EggHeader from "./EggHeader";
import EggHero from "./EggHero";

export default function EasterEgg() {
  return (
    <main className="bg-[url('/images/eggs.JPG')] bg-cover min-h-screen">
      <EggHeader />
      <EggHero />
    </main>
  );
}

//Image generated by Grok by xAI
