import Image from "../Image";
import Users from "./Users";

export default function ToBegin() {
  const ventanas = "/images/windows.jpg";
  return (
    <section className="flex justify-center items-center text-3xl md:text-4xl flex-1">
      <div className="flex flex-col md:flex-row justify-center items-center">
        <div className="flex flex-col gap- justify-center items-center ">
          <div className="flex flex-col md:flex-row md:gap-4">
            <Image
              image={ventanas}
              className="w-50 md:w-50 mx-auto rounded-xl"
              alt="Image of a pink window, image generated by Grok 3"
            />
            <h1 className="font-lobster mt-28 text-vibriantPink">
              Ventanas XP
            </h1>
          </div>
          <p className="text-2xl mr-4 md:mr-12 mt-4">
            To begin, click on your username.
          </p>
        </div>
      </div>
    </section>
  );
}
