import Hero from "./Hero";
import Nav from "./Nav";

export default function SpaceExploration() {
  return (
    <main className="bg-[url('images/earth.jpg')] shadow-xl bg-cover min-h-screen bg-center ">
      <Nav />
      <Hero />
    </main>
  );
}

//background image generated by X's Grok
