import Image from "../Image";

export default function Roxy() {
  return (
    <section className="my-20 flex justify-center items-center">
      <div className="relative">
        <Image
          image="./images/cloud.png"
          alt="Cloud Dialogue Bubble, image generated by ChatGPT"
          className="absolute top-60 max-w-xs lg:max-w-md text-center text-sm font-semibold text-black"
        />
        <blockquote className="relative top-88 lg:top-96 left-24 lg:left-30 font-sig flex-wrap text-2xl lg:text-4xl w-40">
          <cite> Not these fireworks again!</cite>
        </blockquote>
        <Image
          image="./images/roxy2.png"
          alt="Roxy laying down on the couch looking to the side, saying not these fireworks again"
          className="max-w-xs md:max-w-3xl lg:max-w-5xl rounded-3xl "
        />
      </div>
    </section>
  );
}
